### ISSUE TITLE
I can help with level design

### ISSUE THREAD

**Issue by TWHG3And42021Pls** [TheTastyPi/just-a-platformer-2#2]
Hello TheTastyPi,

I don't know if I should put this in 'issues,' but I couldn't find anywhere else to place it. Feel free to delete this if this is in the wrong spot. 

With that out of the way, I enjoy making levels on games, and I could help by making some levels on your released editor. If you do not need help, tell me, and I'll leave you alone. If you want help, please tell me what I should keep in mind when designing a level. For example, should I place all blocks on the grid? What size blocks should I put? Should I retain your idea of 'branches' from the original game, and what features would be on each branch?

Sombody (yes, I know, that is intentionally misspelled), A fan of 'Just a platformer' (mostly EZR because that's the only mode I can beat the game on).

**Comment by TheTastyPi** [comment]
Sorry that I didn't see this earlier, I don't often check the issues here since pretty much nothing comes here.

I may consider allowing user-made levels into the main game of jap2, but I would like to be able to discuss this in a more appropriate location than in the issues tab. As such, would you consider joining the Discord server for my work? The link should be in the "More" tab in jap1. I won't force you to join if you don't wish to. Feel free to propose other methods of communication.

I'll keep this open so that you can reply.

**Comment by TheTastyPi** [comment]
It's been a while, so... I guess I'll close this
